
title = "Androcode"
baseurl = "https://irha.my.id"

# Agar front-matter pakai format YAML
MetaDataFormat = "yaml"

# untuk apply temanya
themesDir = "themes"
theme = "wewe"

# Shortname disqus, silahkan sesuaikan
DisqusShortname = "irhamidn"

# Untuk Google Analytic, silahkan sesuikan
googleAnalytics = "G-S9W0XLD1HE"

ignoreLogs = ['warning-goldmark-raw-html']

[markup.goldmark.renderer]
  unsafe = true


# Untuk deskripsi tag meta di homepage
# Biodata Author
[params]
    author = "Irham"
    homepage = "https://github.com/irhamfa"
    bio = "Asik By : Susanti"
    authorImage = "/img/face.svg"



    Description = "Make a Move : Learn by learn"

	keywords  = [
    "sass", "ssg", "static site",
    "jekyll", "hugo", "hexo", "11ty", "eleventy",
    "bootstrap", "bulma", "materialize", "python", "html",
    "django", "flask", "c/c++", "java", "css", "sass",
    "linux", "tailwindcss", "flask", "django", "html"
  ]

[security]
  allowContent = ['^text/html$']

  allowContent = 'none'
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^node$', '^postcss$', '^tailwindcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE|PROGRAMDATA)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['(?i)^https?://[a-z0-9]', '! ^https?://\d+\.', '! (?i)localhost', '! (?i)^https?://[^/?#]*@']

  [security.node]
    [security.node.permissions]
      allowAddons = ['tailwindcss']
      allowChildProcess = ['tailwindcss']
      allowRead = ['.']
      allowWorker = ['tailwindcss']
      allowWrite = []
      disable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[outputs]
  section = ["html", "rss", "json"]

[[menu.main]]
    name = "Categories"
    url = "/categories"

enableRobotsTXT = true

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
